 version: '2'
 services:
   db:
     image: postgres
     volumes:
       - ./postgres-data/:/var/lib/postgresql
   web:
     build: .
     command: /entrypoint.sh
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
