# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('commit_amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='url',
        ),
        migrations.AddField(
            model_name='repo',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='contributor',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.Repo'),
        ),
    ]
