# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20170501_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='commit_amount',
            field=models.CharField(max_length=50),
        ),
    ]
